### ISSUE TITLE
Support for v12 LTS planned?

### ISSUE THREAD

**Issue by tomkyle** [jweiland-net/replacer#20]
Are there any plans to support Typo3 12.4 LTS? 

Thanks for your work on this extension!
A Typo3 newbie

**Comment by Denneee** [comment]
Any new informations for a possible TYPO3 v12 Release?

**Comment by sfroemkenjw** [comment]
We are just working on it: https://github.com/jweiland-net/replacer/tree/typo3_12_compatibility

**Comment by xerc** [comment]
@sfroemkenjw 
"from version 3. We made the individual processing of search replacement key"
PLEASE re-integrate the global `enable_regex` or check for `/` to activate each line

**Comment by xerc** [comment]
all my rules are regex therefore it would be convenient to enable globaly (inkl. no need for other checks)

**Comment by sfroemkenjw** [comment]
Good Morning @xerc 

of cause, we are speaking here in a range of microseconds, but using `preg_replace` is 28% slower than `str_replace` and as more complex the RegExp is, it's up to 40% slower. PhpStorm plugin prefers using `str_replace` instead of `preg_replace`, if it detects simple word replacements. In TYPO3 core the redirect records will be grouped by RegExp to execute them at last, to prevent interrupting the fast redirects. And, of cause, you have to activate RegExp for each redirect individually.

So, for sure, you now have to adopt all of your settings. But now we prefer the option to speed up our extension a little bit and give other users much more flexible.
